config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "confirmations"}

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  root :to => 'static_pages#index'

  resources :groups
  resources :roles
  resources :users do
    member do
      get :properties
      get :remind_to_send_counters
    end
  end

  resources :reports do
    collection do
      get :monthly_counters
    end
  end

  resources :villages do
    member do
      get :users
    end
    resources :properties do
      member do
        patch :send_counters
      end
      resources :meterings
    end
    resources :counters do
      resources :tariffs
    end
  end


end

app/models/property.rb
class Property < ActiveRecord::Base

  PROPERTY_TYPES = ['таунхаус', 'дуплекс', 'коттедж']

  belongs_to :user
  belongs_to :village
  has_many :meterings, inverse_of: :property

  validates :title, presence: true

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy, :meterings, :send_counters]
  before_action :set_parents

  def index
    @items = @village.properties
  end

  def show

  end

  def edit

  end

  def meterings
    @counters = @item.village.counters
    @counter =  @counters.first
    @counter =  Counter.find(params[:counter_id]) if params[:counter_id]
    @items = @counter.meterings.where(user_id: @item.id).order('year DESC, month DESC')
  end

  def new
    @property = @item = Property.new
  end

  def update
    if @item.update(item_params)
      redirect_to edit_village_property_path(@village, @item), notice: 'Изменения сохранены'
    else
      render "villages/edit"
    end
  end

  def create
    @item = Property.new(item_params)
    if @item.save
      redirect_to village_properties_path(@village), notice: 'Создано'
    else
      render :new, notice: 'Ошибка'
    end
  end

  def destroy
    if @item.destroy
      redirect_to village_properties_path(@village), notice: 'Удалено'
    else
      redirect_to village_properties_path(@village), notice: 'Ошибка при удалении'
    end
  end

  def send_counters
    if params[:counters].size > 0 && params[:month] && params[:year]
      params[:counters].keys.each do |c|
        counter = Counter.find_by(id: c)
        if counter
          tariff_id =  counter.tariff_for_month( params[:month].to_i, params[:year].to_i ).try(:id)
          hash = { tariff_id: tariff_id, property_id: @item.id, month: params[:month], year: params[:year] }
          metering = Metering.find_by(hash)
          if metering
            metering.update_attribute( 'value', params[:counters][c] )
          else
            Metering.create( hash.merge!({value: params[:counters][c] }) )
          end
        end
      end
    end
    redirect_to root_path
  end

  private

  def item_params
    params[:property].permit(:title, :user_id, :village_id, :ptype )
  end

  def set_item
    @village = @item = Property.find(params[:id])
  end

  def set_parents
    @village = Village.find(params[:village_id])
  end

end

app/views/properties/_breadcrumbs.html.haml
%ul.breadcrumb
  %li= link_to 'Счетчики', village_counters_path(@village)
  %li= @item.title

app/views/properties/_form.html.haml
= render "shared/error_messages", :target => @item

= form_for @item, url: form_action, html: {class: 'form form-horizontal'} do |f|
  = f.hidden_field :village_id, :value => @village.id
  .form-group
    .col-sm-3
      %label Название
    .col-sm-5
      = f.text_field :title, class: 'form-control',  :autofocus=>true

  .form-group
    .col-sm-3
      %label Владелец
    .col-sm-5
      = f.select :user_id, @village.users.map{|c| [c.title, c.id]}, { class: 'form-control'}

  .form-group
    .col-sm-3
      %label Тип
    .col-sm-5
      = f.select :ptype, Property::PROPERTY_TYPES.map{|c| [c, c]}, { class: 'form-control'}

  .form-group
    .col-sm-12
      = f.submit 'Сохранить', class: 'btn btn-success'
      %a.btn.btn-default{href: request.referer} Отмена
      - unless @item.new_record?
        = link_to 'Удалить', village_property_path(@village, @item), method: :delete, class: 'btn btn-danger pull-right', confirm: 'Подтвердите удаление'

app/views/properties/_table.html.haml
.row
  .col-sm-12
    - if @items.any?
      %table.table.table-stripped.table-hover
        %thead
          %tr
            %th #
            %th.col-sm-4 Название
            %th.col-sm-4 Тип
            %th.col-sm-4 Владелец
        %tbody
          - @items.each_with_index do |item, index|
            %tr
              %td= index+1
              %td= link_to item.title, edit_village_property_path(@village.id, item.id)
              %td= item.ptype
              %td
                - if item.user
                  = item.user.title

    - else
      %p Нет объектов

app/views/properties/_tabs.html.haml
%ul.nav.nav-tabs.offset-top-20
  = tab "Общая", edit_village_property_path(@village, @item)
  = tab "Показания счетчиков", village_property_meterings_path(@village, @item)

app/views/properties/edit.html.haml
= render 'breadcrumbs'
= render 'tabs'

%h3 Редактировать
%br
= render partial: 'form', locals: {form_action: village_property_path(@village, @item)}

app/views/properties/index.html.haml
= render "villages/tabs"

.row
  .col-md-10.col-lg-10.col-xs-7
    %h3 Объекты
  .col-sm-2.pull-right.top20
    = link_to "Создать", new_village_property_path(@village.id), class: "btn btn-primary btn-sm"

= render 'table'

app/views/properties/meterings.html.haml
= render 'breadcrumbs'

= render 'tabs'

.row
  .col-md-12
    %h3 Показания

= render 'meterings/table'

app/views/properties/new.html.haml
= render 'breadcrumbs'

%h3 Новый объект
%br
= render partial: 'form', locals: {form_action: village_properties_path(@village, @item)}