config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "confirmations"}

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  root :to => 'static_pages#index'

  resources :groups
  resources :roles
  resources :users do
    member do
      get :properties
      get :remind_to_send_counters
    end
  end

  resources :reports do
    collection do
      get :monthly_counters
    end
  end

  resources :villages do
    member do
      get :users
    end
    resources :properties do
      member do
        patch :send_counters
      end
      resources :meterings
    end
    resources :counters do
      resources :tariffs
    end
  end


end

app/models/tariff.rb
class Tariff < ActiveRecord::Base
  belongs_to :counter
  has_one :village, through: :counter
  has_many :meterings, inverse_of: :tariff

  validates :rate, presence: true

  def date
    DateTime.new(year,month).strftime("%m.%Y")
  end

  def full_title
    "#{rate} от #{date}"
  end

end

app/controllers/tariffs_controller.rb
class TariffsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_parents
  before_action :set_env
  before_action :authenticate_user!

  def index
    @items = @counter.tariffs
  end

  def show
    redirect_to :action => "edit"
  end

  def edit

  end

  def new
    @item = @counter.tariffs.new
  end

  def update
    if @item.update(item_params)
      redirect_to village_counter_tariffs_path(@village, @counter), notice: 'Изменения сохранены'
    else
      render "tariffs/edit"
    end
  end

  def create
    @item = @counter.tariffs.new(item_params)
    if @item.save
      redirect_to village_counter_tariffs_path(@village, @counter), notice: 'Создано'
    else
      render :edit, notice: 'Ошибка'
    end
  end

  def destroy
    if @item.destroy
      redirect_to village_counter_tariffs_path(@village, @counter), notice: 'Удалено'
    else
      redirect_to village_counter_tariffs_path(@village, @counter), notice: 'Ошибка при удалении'
    end
  end

  private

  def set_env
    if @item
      @counter = @item.counter
      @village = @item.village
    elsif params[:counter_id]
      @counter = Counter.find(params[:counter_id])
      @village = @counter.village if @counter
    end
  end

  def item_params
    params[:tariff][:rate] = params[:tariff][:rate].gsub(',', '.') if params[:tariff][:rate]

    params[:tariff].permit(:year, :month, :rate)
  end

  def set_item
    @item = Tariff.find(params[:id])
  end

  def set_parents
    @village = Village.find(params[:village_id])
    @counter = Counter.find(params[:counter_id])
  end

end

app/views/tariffs/_breadcrumbs.html.haml
%ul.breadcrumb
  %li= link_to 'Счетчики', village_counters_path(@village)
  %li= link_to @counter.title, edit_village_counter_path(@village, @counter)

app/views/tariffs/_form.html.haml
= form_for @item, url: form_action, html: {class: 'form form-horizontal'} do |f|
  .form-group
    .col-sm-3
      %label Месяц
    .col-sm-9
      = f.select :month, options_for_select(Common::MONTHS, @item.month), { class: 'form-control'}
  .form-group
    .col-sm-3
      %label Год
    .col-sm-9
      = f.select :year, (Time.now.year-4...Time.now.year+2).map{|c| [c, c]}, { class: 'form-control'}
  -#.form-group
  -#  .col-sm-3
  -#    %label Счетчик
  -#  .col-sm-9
  -#    = f.select :counter_id, @village.counters.map{|c| [c.title, c.id]}, { class: 'form-control'}

  .form-group
    .col-sm-3
      %label Значение
    .col-sm-2
      = f.text_field :rate, class: 'form-control'


  .form-group
    .col-sm-12
      = f.submit 'Сохранить', class: 'btn btn-success'
      %a.btn.btn-default{href: request.referer} Отмена
      - unless @item.new_record?
        = link_to 'Удалить', village_counter_tariff_path(@village, @counter, @item), method: :delete, class: 'btn btn-danger pull-right', confirm: 'Подтвердите удаление'

app/views/tariffs/_tabs.html.haml
%ul.nav.nav-tabs.offset-top-20
  = tab "Общая", edit_counter_path(@item)
  = tab "Тарифы", tariffs_counter_path(@item)

app/views/tariffs/edit.html.haml
= render 'breadcrumbs'

%h3 Редактировать
%br
= render partial: 'form', locals: {form_action: village_counter_tariff_path(@village, @counter, @item)}

app/views/tariffs/index.html.haml
= render 'breadcrumbs'

.row
  .col-md-10.col-lg-10.col-xs-7
    %h3 Тарифы счетчика
  .col-sm-2.pull-right.top20
    = link_to "Добавить", new_village_counter_tariff_path(@village, @counter), class: "btn btn-primary btn-sm"
.row
  .col-sm-12
    - if @items.to_a.size > 0
      %table.table.table-stripped.table-hover
        %thead
          %trCou
            %th #
            %th.col-sm-8 Месяц
            %th.col-sm-4 Тариф
        %tbody
          - @items.each_with_index do |item, index|
            %tr
              %td= index+1
              %td= link_to item.date, edit_village_counter_tariff_path(@village, @counter, item)
              %td= link_to item.rate, edit_village_counter_tariff_path(@village, @counter, item)

    - else
      %p Нет тарифов

app/views/tariffs/new.html.haml
= render 'breadcrumbs'

%h3 Добавить тариф
%br
= render partial: 'form', locals: {form_action: village_counter_tariffs_path(@village, @counter)}