config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "confirmations"}

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  root :to => 'static_pages#index'

  resources :groups
  resources :roles
  resources :users do
    member do
      get :properties
      get :remind_to_send_counters
    end
  end

  resources :reports do
    collection do
      get :monthly_counters
    end
  end

  resources :villages do
    member do
      get :users
    end
    resources :properties do
      member do
        patch :send_counters
      end
      resources :meterings
    end
    resources :counters do
      resources :tariffs
    end
  end


end

app/models/village.rb
class Village < ActiveRecord::Base

  validates :code, presence: true
  validates :code, uniqueness: true
  has_many :users, inverse_of: :village,  primary_key: 'code', foreign_key: 'village_code'
  has_many :counters, inverse_of: :village,  primary_key: 'code', foreign_key: 'village_code'
  has_many :properties, inverse_of: :village

end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy, :users, :counters]

  def index
    @items = Village.all
  end

  def show
    redirect_to :action => "edit"
  end

  def edit

  end

  def new
    @village = @item = Village.new
  end

  def update
    if @item.update(item_params)
      redirect_to edit_village_path(@item), notice: 'Изменения сохранены'
    else
      render "villages/edit"
    end
  end

  def users
    @items = User.where(village_code: @item.code)
  end

  def create
    @item = Village.new(item_params)
    if @item.save
      redirect_to villages_path, notice: 'Создано'
    else
      render :new, notice: 'Ошибка'
    end
  end

  def destroy
    if @item.destroy
      redirect_to villages_path, notice: 'Удалено'
    else
      redirect_to villages_path, notice: 'Ошибка при удалении'
    end
  end

  private

  def item_params
    params[:village].permit(:title, :code )
  end

  def set_item
    @village = @item = Village.find(params[:id])
  end

end

app/views/villages/_breadcrumbs.html.haml
%ul.breadcrumb
  %li= link_to 'Организации', villages_path
  %li= link_to @village.title, village_path(@village)

app/views/villages/_form.html.haml
= form_for @item, url: form_action, html: {class: 'form form-horizontal'} do |f|
  .form-group
    .col-sm-3
      %label Название
    .col-sm-6
      = f.text_field :title, class: 'form-control',  :autofocus=>true
  .form-group
    .col-sm-3
      %label Код
    .col-sm-6
      = f.text_field :code, class: 'form-control'


  .form-group
    .col-sm-12
      = f.submit 'Сохранить', class: 'btn btn-success'
      %a.btn.btn-default{href: request.referer} Отмена
      - unless @item.new_record?
        = link_to 'Удалить', village_path(@item), method: :delete, class: 'btn btn-danger pull-right', data: {confirm: 'Подтвердите удаление'}

app/views/villages/_tabs.html.haml
%ul.nav.nav-tabs.offset-top-20
  = tab "Общая", edit_village_path(@village)
  = tab "Жители", users_village_path(@village)
  = tab "Объекты", village_properties_path(@village)
  = tab "Счетчики", village_counters_path(@village)

app/views/villages/edit.html.haml
-#= render 'breadcrumbs'

= render 'tabs'

%h3 Редактировать
%br
= render partial: 'form', locals: {form_action: village_path(@item)}

app/views/villages/index.html.haml
.row
  .col-md-10.col-lg-10.col-xs-7
    %h3 Организации
  .col-sm-2.pull-right.top20
    = link_to "Создать", new_village_path, class: "btn btn-primary btn-sm"
.row
  .col-sm-12
    - if @items.any?
      %table.table.table-stripped.table-hover
        %thead
          %tr
            %th #
            %th.col-sm-9 Название
            %th.col-sm-3 Код
        %tbody
          - @items.each_with_index do |item, index|
            %tr
              %td= index+1
              %td= link_to item.title, village_path(item.id)
              %td= item.code

    - else
      %p Нет организаций

app/views/villages/new.html.haml
%ul.breadcrumb
  %li= link_to 'Организации', villages_path
  %li Добавить организацию

%h3 Добавить организацию
%br
= render partial: 'form', locals: {form_action: villages_path(@item)}

app/views/villages/users.html.haml
-#= render "breadcrumbs"
= render 'tabs'

.row
  .col-md-10.col-lg-10.col-xs-7
    %h3 Пользователи
  .col-sm-2.pull-right.top20
    = link_to "Создать", new_user_path(village_id: @item.id), class: "btn btn-primary btn-sm"

= render :partial => 'users/table', locals: {items: @items, village_id: @item.id}