config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:confirmations => "confirmations"}

  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  root :to => 'static_pages#index'

  resources :groups
  resources :roles
  resources :users do
    member do
      get :properties
      get :remind_to_send_counters
    end
  end

  resources :reports do
    collection do
      get :monthly_counters
    end
  end

  resources :villages do
    member do
      get :users
    end
    resources :properties do
      member do
        patch :send_counters
      end
      resources :meterings
    end
    resources :counters do
      resources :tariffs
    end
  end


end

app/models/metering.rb
class Metering < ActiveRecord::Base
  belongs_to :tariff
  belongs_to :user
  belongs_to :property
  has_one :counter, through: :tariff

  validates :value, presence: true

  def self.by_code(code)
    joins(:tariff => :counter).where(counters: {code: code}).order('year DESC, month DESC')
  end

  def date
    DateTime.new(year,month).strftime("%m.%Y")
  end

  def code
    tariff.counter_code
  end

  def total
    res = 0
    res = value * tariff.rate if value && tariff.rate
    res
  end

end

app/controllers/meterings_controller.rb
class MeteringsController < ApplicationController
  include VillageInit
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_parents

  def index
    @counters = @property.village.counters
    @counter =  @counters.first
    @counter =  Counter.find(params[:counter_id]) if params[:counter_id]
    @items = @counter.meterings.where(property_id: @property.id).order('year DESC, month DESC')
  end

  def show
    redirect_to :action => "edit"
  end

  def edit

  end

  def new
    @item = @counter.meterings.new(property_id: @property.id)
    last_metering = @counter.meterings.where(property_id: @property.id).order('year DESC, month DESC').try(:first)
    if last_metering
      next_obj = Helpers::Month.next_month(last_metering.month, last_metering.year)
      @item.year = next_obj[:year]
      @item.month = next_obj[:month]
      @item.tariff = @counter.tariff_for_month(@item.month, @item.year)
    else
      @item.tariff = @counter.tariff_for_month( DateTime.now.month,  DateTime.now.year)
      @item.year = DateTime.now.year
      @item.month =  DateTime.now.month
    end
  end

  def update
    if @item.update(item_params)
      unless item_params[:tariff_id]
        @item.tariff = @item.counter.tariff_for_month(@item.month, @item.year)
        @item.save
      end
      redirect_to village_property_meterings_path(@village, @property, counter_id: @item.counter.id), notice: 'Изменения сохранены'
    else
      render "meterings/edit"
    end
  end



  def create
    @counter = Counter.find(params[:counter_id])
    @item = @property.meterings.new(item_params)

    unless @item.tariff
      @item.tariff = @counter.tariff_for_month(@item.month, @item.year)
    end

    if @item.save
      redirect_to village_property_meterings_path(@village, @property, counter_id: @item.counter.id), notice: 'Создано'
    else
      render :edit, notice: 'Ошибка'
    end
  end

  def destroy
    if @item.destroy
      redirect_to village_property_meterings_path(@village, @property, counter_id: @item.counter.id), notice: 'Удалено'
    else
      redirect_to village_property_meterings_path(@village, @property, counter_id: @item.counter.id), notice: 'Ошибка при удалении'
    end
  end


  private

  def set_parents
    @village = Village.find(params[:village_id])
    @property = Property.find(params[:property_id])
    @counter = Counter.find(params[:counter_id]) if params[:counter_id]
    @counter = @item.counter if @item
  end

  def item_params
    params[:metering].permit(:value, :tariff_id, :year, :month)
  end

  def set_item
    @item = Metering.find(params[:id])
  end

end

app/views/meterings/_breadcrumbs.html.haml
%ul.breadcrumb
  - if current_user.is?(:manager, :administrator) && @village
    %li= link_to 'Объекты', village_properties_path(@village)
  %li= link_to 'Показания', village_property_meterings_path(@village, @property, counter_id: @counter.id)
  %li= @item.date

app/views/meterings/_chart_price.html.haml
%h3 Всего потрачено
%canvas#chart_prirce{width: 400, height: 200}

:javascript
  var ctx_price = $("#chart_prirce");
  var labels = #{raw labels.to_json};

  var myChart = new Chart(ctx_price, {
      type: 'line',
      data: {
          labels: labels,
          datasets: [{
              label: "#{title}",
              data: #{values},
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });

app/views/meterings/_chart_values.html.haml
%h3 График потребления
%canvas#chart_values{width: 400, height: 200}

:javascript
  var ctx_values = $("#chart_values");
  var labels = #{raw labels.to_json};

  var myChart = new Chart(ctx_values, {
      type: 'bar',
      data: {
          labels: labels ,
          datasets: [{
              label: "#{title}",
              data: #{values},
              backgroundColor: 'rgba(255, 99, 132, 0.2)',

              borderColor: 'rgba(255,99,132,1)',
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });

app/views/meterings/_charts.html.haml
- if @counter
  - labels = []
  - values = []
  - values_rub = []
  - items = @items.reverse.to_a
  - title = "#{@counter.title}, #{@counter.unit}"
  - items.each_with_index do |item, i|
    - labels << item.date
    - if i > 0
      - diff = items[i].value - items[i-1].value
    - else
      - diff = items[i].value
    - values << diff
    - values_rub << item.total

  = render partial: 'chart_values', locals: {title: title, labels: labels, values: values }

  - title = "Итого, руб."
  = render partial: 'chart_price', locals: {title: title, labels: labels, values: values_rub }

app/views/meterings/_form.html.haml
= form_for @item, url: form_action, html: {class: 'form form-horizontal'} do |f|
  .form-group
    .col-sm-3
      %label Месяц
    .col-sm-9
      = f.select :month, options_for_select(Common::MONTHS, @item.month), { class: 'form-control'}
  .form-group
    .col-sm-3
      %label Год
    .col-sm-9
      = f.select :year, (Time.now.year-4...Time.now.year+2).map{|c| [c, c]}, { class: 'form-control'}

  - if current_user.is?(:manager, :administrator)
    .form-group
      .col-sm-3
        %label Тариф
      .col-sm-9
        = f.select :tariff_id, @counter.tariffs.map{|c| [c.date, c.id]}, { class: 'form-control'}

  = hidden_field_tag :counter_id, @counter.id

  .form-group
    .col-sm-3
      %label Значение
    .col-sm-2
      = f.text_field :value, class: 'form-control'


  .form-group
    .col-sm-12
      = f.submit 'Сохранить', class: 'btn btn-success'
      %a.btn.btn-default{href: request.referer} Отмена
      - unless @item.new_record?
        = link_to 'Удалить', village_property_metering_path(@village, @property, @item), method: :delete, class: 'btn btn-danger pull-right', confirm: 'Подтвердите удаление'

app/views/meterings/_table.html.haml
- editable = @counter.editable_by_user?(current_user)
.row.top20
  .col-sm-12
    - @counters.each do |c|
      - klass = 'btn-default'
      - klass = 'btn-primary' if @counter.id == c.id
      - klass = 'disabled' unless c.current_tariff
      = link_to c.title, village_property_meterings_path(@village, @property, counter_id: c.id), class: "btn #{klass} btn-sm"

.row
  .col-sm-12
    - if @items.any?
      %table.table.table-stripped.table-hover
        %thead
          %tr
            %th #
            %th.col-sm-3 Дата
            %th.col-sm-3 Показание
            %th.col-sm-3 Тариф
            %th.col-sm-3 Итого
        %tbody
          - @items.each_with_index do |item, index|
            %tr
              %td= index+1
              - if editable
                %td= link_to item.date, village_property_metering_path(@village, @property, item)
                %td= link_to item.value, village_property_metering_path(@village, @property, item)
              - else
                %td= item.date
                %td= item.value
              %td= item.tariff.full_title
              %td= item.total.round(2)

    - else
      %p Нет показаний


- if editable
  .row
    .col-sm-12.top20
      = link_to "Добавить", new_village_property_metering_path(@village, @property, counter_id: @counter.id), class: "btn btn-success btn-sm"

app/views/meterings/edit.html.haml
= render 'breadcrumbs'

%h3 Редактировать
%br
= render partial: 'form', locals: {form_action: village_property_metering_path(@village, @property, @item)}

app/views/meterings/index.html.haml
- if current_user.is?(:manager, :administrator) && @village
  %ul.breadcrumb
    %li= link_to 'Объекты', village_properties_path(@village)
    %li= link_to @property.title, edit_village_property_path(@village, @property)

= render partial: 'table'

= render partial: 'charts'

app/views/meterings/new.html.haml
= render 'breadcrumbs'

%h3 Новое показание
%br
= render partial: 'form', locals: {form_action: village_property_meterings_path(@village, @property)}